### ISSUE TITLE
Any chance of uploading a gerber zip?

### ISSUE THREAD

**Issue by idank** [jimmerricks/chocolad#1]

**Comment by KostkaBrukowa** [comment]
This keyboard looks awesome. Waiting for RGB version. 36 choc spaced RGB keyboard is the only thing I want in life right now. Thank you for making it!

**Comment by jimmerricks** [comment]
![20211103_004750](https://user-images.githubusercontent.com/1627564/141116700-baae8316-4b16-438c-84d2-e7d96c6eac71.jpg)

**Comment by KostkaBrukowa** [comment]
Wow! This keyboard looks epic. And by the way: where did you get this keycapssss?

**Comment by idank** [comment]
https://www.littlekeyboards.com/products/mbk-glow-keycaps

**Comment by jimmerricks** [comment]
I have added the Chocolad RGB files to the repository. Kicad nightly only, sorry. You can find gerbers for the pcb, and switch and base plate in the appropriate directory. In the coming days, I will update the README and post to Reddit. Thanks everyone for your interest in this project and the motivation that I needed to move it along a little bit.

**Comment by KostkaBrukowa** [comment]
Hey @jimmerricks ! I have little question: does the V3 version work? Because I got a bit impatient and ordered the `chocolad-rgb-gerber.zip` version from above and not the new V4 version.

**Comment by jimmerricks** [comment]
It should yeah. There is very little difference between them. I just tidied it up a little and widened the switch pin holes so they're a tad easier to desolder.

**Comment by jimmerricks** [comment]
I have added some better photos here and posted to Reddit. https://www.reddit.com/r/ErgoMechKeyboards/comments/qvkp1w/the_chocolad_now_in_per_key_rgb/
