### ISSUE TITLE
PCB won't open in KiCad v5.1.10 through 5.1.12

### ISSUE THREAD

**Issue by hmngwy** [jimmerricks/chocolad#3]
I also tried opening this with fresh installs (uninstall then install instead of just reinstalls) to no avail. 

It would just say it needs a version from October in pcbview, and show's a syntax error in KiCad.

![image](https://user-images.githubusercontent.com/1647347/142736675-d9487d12-d17a-4701-8c75-65aef2be6165.png)

```
2:03:50 AM: file 'C:\Users\x\Downloads\chocolad-main\chocolad-main\pcb\chocolad.kicad_pro', line 1: '=' expected.
```

Other projects open just fine.

**Comment by hmngwy** [comment]
Nevermind I seem to be having the same issue with other projects that are made with these versions.

**Comment by jimmerricks** [comment]
It is Kicad nightly only I am afraid. I can export the schematic if that is all you need.
