### ISSUE TITLE
QMK Folder

### ISSUE THREAD

**Issue by drewfowler** [jimmerricks/chocolad#4]
I am curious if you can share your QMK folder? I thought it would be worth it to reach out before I do too much digging. I uploaded the dracula code from qmk but the buttons are all mirrored. Thanks

**Comment by jimmerricks** [comment]
You can help me do some testing. The following may or may not work (I was only interested in testing the LEDs) and it needs a better default keymap. Let me know if there are any problems with it. 

* [chocolad_rgb.zip](https://github.com/jimmerricks/chocolad/files/7623246/chocolad_rgb.zip)

**Comment by jimmerricks** [comment]
To get this to work you will need to (at the very least) disable the OLED in the default keymap rules.mk or else ammend the code. I compiled this under an old version of QMK.

**Comment by jimmerricks** [comment]
How'd you get on with this?

**Comment by drewfowler** [comment]
I only got about 30 minutes with it last night but, I just deleted all the files in the default folder but keymap.c and enabled LEDs in the top level rules and it worked. I have only built up one side but it seemed to work great off that. So I will continue building off of that. Thank you!

**Comment by jimmerricks** [comment]
No worries. Good to hear that the OLED is the only thing.
