### ISSUE TITLE
Hotswap

### ISSUE THREAD

**Issue by andrewneyman** [jimmerricks/chocolad#7]
Not really an issue, just wondering if a hotswap version is planned.

**Comment by jimmerricks** [comment]
I plan to make the holes compatible with Mill Max sockets, but not (at this stage) Kailh hotswap sockets.

**Comment by maverick1872** [comment]
@jimmerricks Any news on supporting hotswap?

**Comment by jimmerricks** [comment]
No updates. I have a non-reversible version of this board done with holes large enough to use Mill Max sockets, but I still need to order and test it before deciding if I want to open source it or not.

**Comment by maverick1872** [comment]
Thanks for the update. If you're alright with it I may just see if I can modify it sufficiently myself then as I'd ideally have a 6 col variant personally.
